// Keeps src/Composition.tsx's static script registry in sync with
// src/scripts/*.json, so adding a new daily script never requires a
// hand-edit to the composition file.
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SCRIPTS_DIR = path.join(ROOT, "src", "scripts");
const COMPOSITION_PATH = path.join(ROOT, "src", "Composition.tsx");

// Script ids are filenames and may contain hyphens (e.g.
// "diaspora-remit26"), which aren't valid JS import identifiers — convert
// to camelCase for the local import binding while keeping the registry
// keyed by the real id, so scriptId lookups elsewhere are unaffected.
function toImportName(id) {
  return id.replace(/-([a-zA-Z0-9])/g, (_, c) => c.toUpperCase());
}

export async function syncRegistry() {
  const files = (await fs.readdir(SCRIPTS_DIR)).filter((f) => f.endsWith(".json"));
  const ids = files.map((f) => f.replace(/\.json$/, "")).sort();

  const imports = ids
    .map((id) => `import ${toImportName(id)} from "./scripts/${id}.json";`)
    .join("\n");
  const registryEntries = ids
    .map((id) => `  "${id}": ${toImportName(id)} as VideoScript,`)
    .join("\n");

  let content = await fs.readFile(COMPOSITION_PATH, "utf-8");

  const IMPORTS_RE = /\/\/ REGISTRY-IMPORTS-START[\s\S]*?\/\/ REGISTRY-IMPORTS-END/;
  const ENTRIES_RE = /\/\/ REGISTRY-ENTRIES-START[\s\S]*?\/\/ REGISTRY-ENTRIES-END/;

  if (!IMPORTS_RE.test(content) || !ENTRIES_RE.test(content)) {
    throw new Error(
      "Composition.tsx is missing the REGISTRY-IMPORTS-START/END or REGISTRY-ENTRIES-START/END markers — " +
      "these anchor where this script writes. Restore them (see git history) rather than editing the fragile-anchor regex again."
    );
  }

  content = content.replace(
    IMPORTS_RE,
    `// REGISTRY-IMPORTS-START (auto-generated by pipeline/registry.mjs, do not hand-edit between these markers)\n${imports}\n// REGISTRY-IMPORTS-END`
  );
  content = content.replace(
    ENTRIES_RE,
    `// REGISTRY-ENTRIES-START (auto-generated by pipeline/registry.mjs, do not hand-edit between these markers)\nconst scriptRegistry: Record<string, VideoScript> = {\n${registryEntries}\n};\n// REGISTRY-ENTRIES-END`
  );

  await fs.writeFile(COMPOSITION_PATH, content, "utf-8");
  return ids;
}

const isMain = path.resolve(fileURLToPath(import.meta.url)) === path.resolve(process.argv[1]);
if (isMain) {
  syncRegistry().then((ids) => {
    console.log(`Registry synced: ${ids.join(", ")}`);
  });
}
