// Usage: node pipeline/wordpress-publish.mjs <date>
//    or: node pipeline/wordpress-publish.mjs <date> --weekly
//
// Publishes ONE daily digest article to bharatat100.wordpress.com,
// synthesizing that day's 5 video pillars into a single coherent
// long-form piece — NOT a per-pillar post like every other platform.
// Unlike social platforms, WordPress gets one article a day, timed for
// AFTER the last daily slot fires (Diaspora Dividend, 22:30 IST) via
// its own 23:00 IST slot (WORDPRESS_SLOT_HOUR_IST below) — scheduled
// via WordPress.com's status:"future" + date, same "schedule now,
// publish itself later" pattern as every other platform in this
// pipeline, not an immediate publish (added 2026-09-10; this used to
// always publish immediately, which meant the article had to be run
// manually right at the intended time — now it can be scheduled
// alongside the rest of the day's batch, right after generation).
//
// The article itself is NOT generated by this script — it's written by
// hand (same quality bar as the video scripts: sourced, non-templated,
// genuine prose) and saved as public/wordpress/<date>.json BEFORE this
// script runs, with this shape:
//   {
//     "title": "...",
//     "excerpt": "...",         // 1-2 sentence summary, used as the meta description
//     "bodyHtml": "...",        // the full article body, as WordPress-ready HTML
//     "sources": ["...", "..."] // combined sources across all 5 pillars
//   }
// Run pipeline/wordpress-cover.mjs <date> BEFORE this script — it adds
// coverImageUrl to the same article JSON (a rendered title card with
// that day's 5 headlines), used here as the featured image. Publishing
// without a cover is still allowed (falls back to no featured image)
// but the cover step should normally run first.
//
// --weekly does the same thing but reads public/wordpress/<date>-weekly.json
// instead, for the once-a-week wrap article (paired with the video
// weekly recap, same 7-day cadence).

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { findDayPillars } from "./wordpress-cover.mjs";
import { nextSlotUtc } from "./slots.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const TOKEN_PATH = path.join(ROOT, "wordpress-token.json");

// 23:00 IST — 30 minutes after Diaspora Dividend (22:30 IST, the last of
// the 5 daily slots), so the digest article always follows all 5 pillars
// actually going live that day, matching this pillar's original design
// ("timed for AFTER the last daily slot fires"). Not in slots.mjs's
// SLOT_HOURS_IST since WordPress isn't a per-pillar platform — it's its
// own once-daily slot, defined here where it's actually used.
const WORDPRESS_SLOT_HOUR_IST = 23;

async function getToken() {
  return JSON.parse(await fs.readFile(TOKEN_PATH, "utf-8"));
}

async function uploadFeaturedImage({ blogId, accessToken, imageUrl, altText, title }) {
  const url = `https://public-api.wordpress.com/rest/v1.1/sites/${blogId}/media/new`;
  const res = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams({
      "media_urls[0]": imageUrl,
      "attrs[0][alt]": altText,
      "attrs[0][title]": title,
    }),
  });
  const json = await res.json();
  if (json.error) throw new Error(`Media upload failed: ${json.message ?? json.error}`);
  const media = json.media?.[0];
  if (!media) throw new Error(`Media upload returned no media item.`);
  return media.ID;
}

async function createPost({ blogId, accessToken, title, excerpt, bodyHtml, tags, categories, featuredImageId, scheduledAtIso }) {
  const url = `https://public-api.wordpress.com/rest/v1.1/sites/${blogId}/posts/new`;
  const body = {
    title,
    content: bodyHtml,
    excerpt,
    // "future" + a future `date` schedules the post — WordPress.com
    // auto-publishes it at that instant, same pattern as every other
    // platform in this pipeline (YouTube's publishAt, Facebook's
    // scheduled_publish_time). Falls back to immediate "publish" if no
    // scheduledAtIso is given (e.g. manual same-day catch-up runs).
    status: scheduledAtIso ? "future" : "publish",
    tags: tags.join(","),
    categories: categories.join(","),
  };
  if (scheduledAtIso) body.date = scheduledAtIso;
  if (featuredImageId) body.featured_image = featuredImageId;

  const res = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });
  const json = await res.json();
  if (json.error) throw new Error(`WordPress publish failed: ${json.message ?? json.error}`);
  return json; // { ID, URL, ... }
}

// Added 2026-09-14: a source entry can now be a plain string (unchanged,
// existing behavior — every source written before this date) OR an object
// {text, url} for a clickable link. This is deliberately backward-
// compatible rather than a breaking schema change — old plain-string
// sources keep working exactly as before, new ones can opt into a real
// link. Scoped to WordPress/Substack/Medium only (not video captions or
// social platforms), per the user's own explicit call: a URL isn't
// clickable in an Instagram/X caption anyway and just adds clutter to an
// already-tight character budget, but a long-form reader can actually
// click through on these three platforms.
function renderSourceItem(source) {
  if (typeof source === "string") return source;
  if (source && typeof source === "object" && source.url) {
    return `<a href="${source.url}" target="_blank" rel="noopener">${source.text ?? source.url}</a>`;
  }
  return source?.text ?? String(source);
}

function buildSourcesHtml(sources) {
  if (!sources?.length) return "";
  const items = sources.map((s) => `<li>${renderSourceItem(s)}</li>`).join("\n");
  return `\n<h3>Sources &amp; Further Reading</h3>\n<ul>\n${items}\n</ul>\n`;
}

async function main() {
  const date = process.argv[2];
  const isWeekly = process.argv.includes("--weekly");
  if (!date) {
    console.error("Usage: node pipeline/wordpress-publish.mjs <date> [--weekly]");
    process.exit(1);
  }

  const articlePath = path.join(ROOT, "public", "wordpress", `${date}${isWeekly ? "-weekly" : ""}.json`);
  let article;
  try {
    article = JSON.parse(await fs.readFile(articlePath, "utf-8"));
  } catch {
    throw new Error(
      `No article found at public/wordpress/${date}${isWeekly ? "-weekly" : ""}.json — write it first (see this script's header comment for the expected shape).`
    );
  }

  const { accessToken, blogId, blogUrl } = await getToken();

  console.log(`\n=== Publishing ${isWeekly ? "weekly wrap" : "daily digest"} article for ${date} to ${blogUrl} ===`);
  console.log(`Title: ${article.title}`);

  // Categories = that day's actual pillars (Sector Futures, Builder
  // Story, etc.) so the blog naturally organizes into archive pages per
  // pillar. Tags stay as broad discovery keywords, separate from
  // categories — WordPress treats the two differently for navigation vs.
  // search/browse.
  const dayPillars = isWeekly ? [] : await findDayPillars(date);
  const categories = isWeekly ? ["Weekly Recap"] : dayPillars.map((p) => p.pillar);
  const tags = isWeekly
    ? ["Bharat100", "WeeklyRecap", "India2047"]
    : ["Bharat100", "India2047", "ViksitBharat", ...dayPillars.map((p) => p.pillar.replace(/\s+/g, ""))];

  const bodyHtml = article.bodyHtml + buildSourcesHtml(article.sources);

  // Only schedule (not immediately publish) when that instant is
  // actually still in the future — a manual catch-up run for a PAST
  // date (e.g. backfilling a day that was missed) should publish right
  // away, not silently fail or schedule into the past.
  const slotAtIso = isWeekly ? null : nextSlotUtc(WORDPRESS_SLOT_HOUR_IST, date);
  const scheduledAtIso = slotAtIso && new Date(slotAtIso).getTime() > Date.now() ? slotAtIso : null;
  if (slotAtIso && !scheduledAtIso) {
    console.log(`Slot time ${slotAtIso} is already in the past — publishing immediately instead of scheduling.`);
  } else if (scheduledAtIso) {
    console.log(`Scheduling for: ${scheduledAtIso} (UTC)`);
  }

  let featuredImageId = null;
  if (article.coverImageUrl) {
    console.log(`Uploading featured image...`);
    // Alt text names the actual headlines, not just the article title —
    // better for image search discoverability than a generic caption.
    const altText = isWeekly
      ? `Bharat@100 weekly recap cover, ${date}`
      : `Bharat@100 daily digest cover, ${article.coverDate ?? date}: ${(article.coverHeadlines ?? []).join(" | ")}`;
    featuredImageId = await uploadFeaturedImage({
      blogId,
      accessToken,
      imageUrl: article.coverImageUrl,
      altText,
      title: article.title,
    });
  } else {
    console.log(`No coverImageUrl on this article — run pipeline/wordpress-cover.mjs ${date} first for a featured image. Publishing without one.`);
  }

  const result = await createPost({
    blogId,
    accessToken,
    title: article.title,
    excerpt: article.excerpt,
    bodyHtml,
    tags,
    categories,
    featuredImageId,
    scheduledAtIso,
  });

  console.log(scheduledAtIso ? `Scheduled: ${result.URL}` : `Published: ${result.URL}`);

  article.wordpressPostId = result.ID;
  article.wordpressUrl = result.URL;
  if (scheduledAtIso) {
    article.wordpressScheduledAt = scheduledAtIso;
  } else {
    article.publishedAt = new Date().toISOString();
  }
  await fs.writeFile(articlePath, JSON.stringify(article, null, 2), "utf-8");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
