import React from "react";
import { CalculateMetadataFunction, Composition, staticFile } from "remotion";
import { VideoTemplate, VideoScript, SceneTiming } from "./VideoTemplate";

type InputProps = {
  scriptId: string;
};

type ResolvedProps = InputProps & {
  script: VideoScript;
  timings: SceneTiming[];
  outroTiming: SceneTiming;
  audioFile: string;
};

type Manifest = {
  scriptId: string;
  audioFile: string;
  timings: SceneTiming[];
  outroTiming: SceneTiming;
  totalDurationInFrames: number;
  fps: number;
};

// REGISTRY-IMPORTS-START (auto-generated by pipeline/registry.mjs, do not hand-edit between these markers)
import ashokkhade26 from "./scripts/ashokkhade26.json";
import batteryStorage26 from "./scripts/battery-storage26.json";
import budget from "./scripts/budget.json";
import cgsemi26 from "./scripts/cgsemi26.json";
import cynlr26 from "./scripts/cynlr26.json";
import defence26 from "./scripts/defence26.json";
import diasporaFcnr26 from "./scripts/diaspora-fcnr26.json";
import diasporaPhilanthropy26 from "./scripts/diaspora-philanthropy26.json";
import diasporaRealestate26 from "./scripts/diaspora-realestate26.json";
import diasporaRemit26 from "./scripts/diaspora-remit26.json";
import diasporaTourism26 from "./scripts/diaspora-tourism26.json";
import diasporaVc26 from "./scripts/diaspora-vc26.json";
import diasporaceos26 from "./scripts/diasporaceos26.json";
import diasporagiving26 from "./scripts/diasporagiving26.json";
import diasporaincome26 from "./scripts/diasporaincome26.json";
import electronics26 from "./scripts/electronics26.json";
import evgrowth26 from "./scripts/evgrowth26.json";
import exportsrecord26 from "./scripts/exportsrecord26.json";
import galaxeye26 from "./scripts/galaxeye26.json";
import isrochip26 from "./scripts/isrochip26.json";
import jainwolf26 from "./scripts/jainwolf26.json";
import kalpanasaroj26 from "./scripts/kalpanasaroj26.json";
import kewalramani26 from "./scripts/kewalramani26.json";
import nfapunicorns26 from "./scripts/nfapunicorns26.json";
import panchanathan26 from "./scripts/panchanathan26.json";
import pharmaexports26 from "./scripts/pharmaexports26.json";
import pixxel26 from "./scripts/pixxel26.json";
import pmrc26 from "./scripts/pmrc26.json";
import portslogistics26 from "./scripts/portslogistics26.json";
import renewables26 from "./scripts/renewables26.json";
import repm26 from "./scripts/repm26.json";
import semicon2 from "./scripts/semicon2.json";
import semiconductors from "./scripts/semiconductors.json";
import skills2030 from "./scripts/skills2030.json";
import solarmfg26 from "./scripts/solarmfg26.json";
import spacetech26 from "./scripts/spacetech26.json";
// REGISTRY-IMPORTS-END

// REGISTRY-ENTRIES-START (auto-generated by pipeline/registry.mjs, do not hand-edit between these markers)
const scriptRegistry: Record<string, VideoScript> = {
  "ashokkhade26": ashokkhade26 as VideoScript,
  "battery-storage26": batteryStorage26 as VideoScript,
  "budget": budget as VideoScript,
  "cgsemi26": cgsemi26 as VideoScript,
  "cynlr26": cynlr26 as VideoScript,
  "defence26": defence26 as VideoScript,
  "diaspora-fcnr26": diasporaFcnr26 as VideoScript,
  "diaspora-philanthropy26": diasporaPhilanthropy26 as VideoScript,
  "diaspora-realestate26": diasporaRealestate26 as VideoScript,
  "diaspora-remit26": diasporaRemit26 as VideoScript,
  "diaspora-tourism26": diasporaTourism26 as VideoScript,
  "diaspora-vc26": diasporaVc26 as VideoScript,
  "diasporaceos26": diasporaceos26 as VideoScript,
  "diasporagiving26": diasporagiving26 as VideoScript,
  "diasporaincome26": diasporaincome26 as VideoScript,
  "electronics26": electronics26 as VideoScript,
  "evgrowth26": evgrowth26 as VideoScript,
  "exportsrecord26": exportsrecord26 as VideoScript,
  "galaxeye26": galaxeye26 as VideoScript,
  "isrochip26": isrochip26 as VideoScript,
  "jainwolf26": jainwolf26 as VideoScript,
  "kalpanasaroj26": kalpanasaroj26 as VideoScript,
  "kewalramani26": kewalramani26 as VideoScript,
  "nfapunicorns26": nfapunicorns26 as VideoScript,
  "panchanathan26": panchanathan26 as VideoScript,
  "pharmaexports26": pharmaexports26 as VideoScript,
  "pixxel26": pixxel26 as VideoScript,
  "pmrc26": pmrc26 as VideoScript,
  "portslogistics26": portslogistics26 as VideoScript,
  "renewables26": renewables26 as VideoScript,
  "repm26": repm26 as VideoScript,
  "semicon2": semicon2 as VideoScript,
  "semiconductors": semiconductors as VideoScript,
  "skills2030": skills2030 as VideoScript,
  "solarmfg26": solarmfg26 as VideoScript,
  "spacetech26": spacetech26 as VideoScript,
};
// REGISTRY-ENTRIES-END

const loadScript = (scriptId: string): VideoScript => {
  const script = scriptRegistry[scriptId];
  if (!script) throw new Error(`No script found for id "${scriptId}"`);
  return script;
};

const loadManifest = async (scriptId: string): Promise<Manifest> => {
  const res = await fetch(staticFile(`${scriptId}/timings.json`));
  if (!res.ok) {
    throw new Error(
      `No timings.json found for "${scriptId}". Run: node pipeline/build.mjs ${scriptId}`
    );
  }
  return res.json();
};

const calculateMetadata: CalculateMetadataFunction<InputProps> = async ({ props }) => {
  const manifest = await loadManifest(props.scriptId);
  const script = loadScript(props.scriptId);
  return {
    durationInFrames: manifest.totalDurationInFrames,
    fps: manifest.fps,
    props: {
      ...props,
      script,
      timings: manifest.timings,
      outroTiming: manifest.outroTiming,
      audioFile: manifest.audioFile,
    } satisfies ResolvedProps,
  };
};

export const Bharat100Composition = () => {
  return (
    <Composition
      id="Bharat100"
      component={Bharat100Video}
      durationInFrames={300}
      fps={30}
      width={1080}
      height={1920}
      defaultProps={{ scriptId: "semiconductors" } as ResolvedProps}
      calculateMetadata={calculateMetadata}
    />
  );
};

export const Bharat100Video: React.FC<ResolvedProps> = ({
  script,
  timings,
  outroTiming,
  audioFile,
}) => {
  return (
    <VideoTemplate
      script={script}
      timings={timings}
      outroTiming={outroTiming}
      audioFile={audioFile}
      musicFile={null}
    />
  );
};
